### ISSUE TITLE
Running the plugin causes FPS to drop

### ISSUE THREAD

**Issue by Ani-ki** [XIV-Tools/CustomizePlus#8]
Per Maxunit:
> C+ halfs my FPS tho
> as soon as i enable it with a scaling active, it drops my stable 60 fps to 34 - 35 

Unable to repro at this stage but will keep open in the event that anyone else experiences this.

**Comment by ivalith** [comment]
Have also noticed this as of the 0.0.0.3 release, enabling Customize+ drops FPS to 35-40 while unchecking enable and hitting save jumps back up to 60 FPS.
![2022-05-30_00-51-48](https://user-images.githubusercontent.com/57418557/170919413-11b5de94-b206-4b29-9665-a3adb789fb6e.png)
![2022-05-30_00-52-24](https://user-images.githubusercontent.com/57418557/170919417-7d676366-c64a-494b-b255-227c4c139d22.png)

**Comment by dillyrem** [comment]
I also have experienced the frame rate drop. I usually experience 90-100 and I could not go above 60 in a very tame area with the scaler on.

**Comment by Yuki-Codes** [comment]
This has been fixed for the next release

**Comment by Ani-ki** [comment]
> also experiencing fps drops, normal run at 60, while customize plus enabled, drops to as low as 12 Thanks yuki for getting this up and running again! :)

Are you on 0.0.0.4?

**Comment by endmymisery** [comment]
Sorry to comment on an old issue, but there still appears to be frame drops/stuttering when C+ is enabled.
Currently using version 0.0.1.5.

I noticed it happens specifically whenever Dalamud does memory cleanup, roughly every second or two.
